import * as THREE from 'three';

const VERTEX=`varying vec2 vUv;uniform float uFold;uniform float uTime;void main(){vUv=uv;vec3 p=position;p.z+=sin(p.x*3.0+uTime)*.09*uFold+p.y*p.y*.18*uFold;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}`;
const BLUEPRINT_FRAGMENT=`varying vec2 vUv;uniform float uFold;uniform float uTime;void main(){float grid=(step(.96,fract(vUv.x*12.0))+step(.96,fract(vUv.y*10.0)))*.25;float ink=sin(vUv.x*42.0+uTime*.4)*.035*uFold;vec3 paper=mix(vec3(.91,.86,.72),vec3(.46,.63,.75),uFold*.28);gl_FragColor=vec4(paper+grid+ink,1.0);}`;
const ENAMEL_FRAGMENT=`varying vec2 vUv;uniform float uFracture;uniform float uHeal;void main(){float cracks=abs(sin((vUv.x+vUv.y*.7)*58.0))*step(.78,fract(sin(dot(floor(vUv*17.0),vec2(12.9,78.2)))*43758.5));float visible=cracks*uFracture*(1.0-uHeal);vec3 enamel=mix(vec3(.83,.76,.62),vec3(.95,.89,.73),uHeal);gl_FragColor=vec4(enamel-visible*vec3(.52,.2,.15),1.0);}`;
const TIME_FRAGMENT=`varying vec2 vUv;uniform float uTime;uniform float uHostility;void main(){vec2 q=vUv-.5;float r=length(q);float rings=sin(r*46.0-uTime*3.0)*.5+.5;float shards=step(.78,fract(atan(q.y,q.x)*4.0+r*13.0));float a=(rings*.22+shards*.45)*uHostility*smoothstep(.72,.05,r);gl_FragColor=vec4(.18,.33,.55,a);}`;

export class ClockmakerMaterialEffects {
  constructor(kit, quality = 'high') { this.kit=kit;this.quality=quality; }
  blueprintFold({ width=2, height=1.4 }={}) { const m=new THREE.ShaderMaterial({uniforms:{uFold:{value:0},uTime:{value:0}},vertexShader:VERTEX,fragmentShader:BLUEPRINT_FRAGMENT,side:THREE.DoubleSide});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,height,qualitySegments(this.quality)),m);mesh.userData.setFold=(value,time)=>{m.uniforms.uFold.value=value;m.uniforms.uTime.value=time;};return mesh; }
  enamelFace({ radius=1 }={}) { const m=new THREE.ShaderMaterial({uniforms:{uFracture:{value:0},uHeal:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:ENAMEL_FRAGMENT});const mesh=new THREE.Mesh(new THREE.CircleGeometry(radius,48),m);mesh.userData.setEnamel=(fracture,heal)=>{m.uniforms.uFracture.value=fracture;m.uniforms.uHeal.value=heal;};return mesh; }
  timeFractureField({ radius=2 }={}) { const m=new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uHostility:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:TIME_FRAGMENT,transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending});const mesh=new THREE.Mesh(new THREE.CircleGeometry(radius,64),m);mesh.userData.setTimeFracture=(hostility,time)=>{m.uniforms.uHostility.value=hostility;m.uniforms.uTime.value=time;};return mesh; }
  redThreadGlow(points) { const core=this.kit.redThread(points);const glow=new THREE.Mesh(core.geometry.clone(),new THREE.MeshBasicMaterial({color:'#ff7665',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));const root=new THREE.Group();root.add(glow,core);root.userData.setThread=(progress)=>{core.material.opacity=progress;glow.material.opacity=progress*.45;glow.scale.setScalar(1+progress*.16);};return root; }
  tickWave({ rings=4 }={}) { const root=new THREE.Group();const count=this.quality==='high'?rings:this.quality==='medium'?Math.max(2,rings-1):2;for(let i=0;i<count;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.35+i*.14,.022,6,36),new THREE.MeshBasicMaterial({color:'#ffe4a3',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));ring.rotation.x=-Math.PI/2;ring.userData.delay=i*.12;root.add(ring);}root.userData.setTick=(progress)=>root.children.forEach(ring=>{const p=clamp((progress-ring.userData.delay)*2.4);ring.scale.setScalar(.5+p*(5+ring.userData.delay*8));ring.material.opacity=p*(1-p)*.75;});return root; }
  brassWear(material, amount) { if (!material?.color) return; material.color.lerp(new THREE.Color('#63745a'),clamp(amount)*.18); }
  dawnWash(target, amount) { if (!target?.material?.color) return; const material = target.material; if (!material.userData.dawnBase) material.userData.dawnBase = material.color.clone(); material.color.copy(material.userData.dawnBase).lerp(new THREE.Color('#efad76'),clamp(amount)*.35); }
}
function qualitySegments(q){return q==='high'?24:q==='medium'?12:6;}function clamp(v){return Math.max(0,Math.min(1,v));}
