import * as THREE from 'three';
import { ProductionBaseScene } from './ProductionBaseScene.js';
import { ClockmakerApprentice } from './ClockmakerApprentice.js';
import { UnspentHour } from './UnspentHour.js';

const clamp=v=>Math.max(0,Math.min(1,v));const ease=v=>{v=clamp(v);return v*v*(3-2*v)};const win=(p,a,b)=>ease((p-a)/(b-a));
const SHOTS=[
 {at:0,pos:[0,12,15],look:[0,0,0],fov:46},
 {at:.16,pos:[-5.5,5.8,10],look:[-2,1,.2],fov:41},
 {at:.34,pos:[-2.1,3.1,6.5],look:[-1,1.4,.5],fov:35},
 {at:.52,pos:[1.4,3.4,7],look:[1.5,1.8,0],fov:37},
 {at:.72,pos:[3.6,5.5,10],look:[0,8,-3],fov:42},
 {at:.88,pos:[1.5,9,14],look:[0,12,-4],fov:47},
 {at:1,pos:[0,12,17],look:[0,15,-5],fov:50}
];
function shot(p,pos,look){let i=0;while(i<SHOTS.length-2&&p>=SHOTS[i+1].at)i++;const a=SHOTS[i],b=SHOTS[i+1],t=ease((p-a.at)/(b.at-a.at));pos.set(...a.pos).lerp(new THREE.Vector3(...b.pos),t);look.set(...a.look).lerp(new THREE.Vector3(...b.look),t);return a.fov+(b.fov-a.fov)*t;}

// Production city: a tabletop city whose conflicting clock tempos cause
// routes to misalign. The red thread is not decoration; it becomes the only
// navigable route to the tower.
export class ProductionCityDisagreesScene extends ProductionBaseScene {
 build(){const {group:g,kit}=this;this._hand=new THREE.Vector3();this._crown=new THREE.Vector3();this._minuteAnchor=new THREE.Vector3();this._delta=new THREE.Vector3();
  const base=new THREE.Mesh(new THREE.BoxGeometry(18,.45,14),kit.material('wood','#49342a'));base.position.y=-.24;g.add(base);const map=new THREE.Mesh(new THREE.PlaneGeometry(17.4,13.4),kit.material('paper','#e2d5b7'));map.rotation.x=-Math.PI/2;map.position.y=.02;g.add(map);
  this.grid=[];for(let x=-8;x<=8;x+=2){const line=new THREE.Mesh(new THREE.BoxGeometry(.025,.02,13),kit.material('brass','#365b78'));line.position.set(x,.05,0);g.add(line);this.grid.push(line);}for(let z=-6;z<=6;z+=2){const line=new THREE.Mesh(new THREE.BoxGeometry(17,.02,.025),kit.material('brass','#365b78'));line.position.set(0,.05,z);g.add(line);this.grid.push(line);}
  this.buildings=[];this.clocks=[];this.cityLamps=[];for(let i=0;i<64;i++){const w=.62+(i%4)*.17,h=.75+(i%5)*.3,d=.68+(i%3)*.15;const building=kit.miniatureBuilding({w,h,d});const x=-7+(i%10)*1.55,z=-5+Math.floor(i/10)*1.65;building.position.set(x,0,z);g.add(building);this.buildings.push({node:building,base:building.position.clone(),phase:i*.41});if(i%3===0){const face=kit.clockFace({radius:.18+(i%3)*.045});face.position.set(x,h+.35,z+d*.52);g.add(face);this.clocks.push({node:face,phase:i*.57,base:face.position.clone()});}if(i%4===0){const post=new THREE.Mesh(new THREE.BoxGeometry(.04,.48,.04),kit.material('brass','#8a6329'));post.position.set(x+.42,.25,z+.42);g.add(post);const lamp=new THREE.Sprite(new THREE.SpriteMaterial({color:'#ffd47b',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));lamp.position.set(x+.42,.56,z+.42);lamp.scale.setScalar(.32);g.add(lamp);this.cityLamps.push({node:lamp,phase:i*.34});}}
  this.bridges=[];for(let i=0;i<6;i++){const bridge=new THREE.Mesh(new THREE.BoxGeometry(2.1,.14,.55),kit.material('brass',i%2?'#b98942':'#7f5b30'));bridge.position.set(-5+i*2.1,.35,-.7+(i%2)*3.1);bridge.userData={base:bridge.position.clone(),phase:i*.72};g.add(bridge);this.bridges.push(bridge);for(let rail=0;rail<2;rail++){const side=new THREE.Mesh(new THREE.BoxGeometry(2.1,.16,.025),kit.material('brass','#76552f'));side.position.set(bridge.position.x,bridge.position.y+.15,bridge.position.z+(rail?-.25:.25));g.add(side);}}
  this.roads=[];for(let i=0;i<8;i++){const road=new THREE.Mesh(new THREE.BoxGeometry(14,.018,.14),kit.material('brass','#3a6079'));road.position.set(0,.08,-5+i*1.65);road.userData={base:road.position.clone(),phase:i*.52,axis:'x'};g.add(road);this.roads.push(road);}for(let i=0;i<10;i++){const road=new THREE.Mesh(new THREE.BoxGeometry(.14,.018,10),kit.material('brass','#3a6079'));road.position.set(-7+i*1.55,.08,0);road.userData={base:road.position.clone(),phase:i*.43,axis:'z'};g.add(road);this.roads.push(road);}
  this.routeTiles=[];for(let i=0;i<26;i++){const tile=new THREE.Mesh(new THREE.PlaneGeometry(.72,.72),kit.material('paper',i%3?'#dcd0b1':'#c7d1c6'));tile.rotation.x=-Math.PI/2;tile.userData={base:new THREE.Vector3(-6.4+(i%8)*1.62,.11,-4.8+Math.floor(i/8)*1.58),phase:i*.31};tile.position.copy(tile.userData.base);g.add(tile);this.routeTiles.push(tile);}
  this.paperRoutes=[];for(let i=0;i<12;i++){const plan=kit.blueprint({width:.85+(i%3)*.2,height:.58});plan.userData={base:new THREE.Vector3(-6+(i%6)*2.4,.3+Math.floor(i/6)*.4,-5+(i%4)*2.7),phase:i*.41};plan.position.copy(plan.userData.base);plan.rotation.x=-Math.PI/2;g.add(plan);this.paperRoutes.push(plan);}
  this.looseTrail=[];for(let i=0;i<this.tiered(42,26,14);i++){const mark=new THREE.Mesh(new THREE.PlaneGeometry(.035,.16),new THREE.MeshBasicMaterial({color:'#c53a35',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));mark.userData={offset:i*.025,phase:i*.42};g.add(mark);this.looseTrail.push(mark);}
  this.train=kit.train();this.train.position.set(-7.3,.3,4.8);g.add(this.train);this.trainTrack=new THREE.Mesh(new THREE.BoxGeometry(15,.035,.18),kit.material('brass','#76552f'));this.trainTrack.position.set(0,.14,4.8);g.add(this.trainTrack);
  this.streetClock=kit.clockFace({radius:.82});this.streetClock.position.set(-2.4,1.35,.8);g.add(this.streetClock);this.unspentHour=new UnspentHour(kit,{particleCount:this.tiered(56,34,18),scale:.55}).attachTo(this.streetClock,new THREE.Vector3(0,0,.18));this.crown=new THREE.Object3D();this.crown.position.set(0,.93,.15);this.streetClock.add(this.crown);
  this.looseHand=new THREE.Group();const hand=new THREE.Mesh(new THREE.BoxGeometry(.1,1.3,.07),kit.material('brass','#b33432'));hand.position.y=.65;this.looseHand.add(hand);this.looseHand.position.set(.9,1.3,.15);g.add(this.looseHand);this.looseAnchor=new THREE.Object3D();this.looseAnchor.position.set(0,1.3,.1);this.looseHand.add(this.looseAnchor);
  this.tower=new THREE.Group();this.tower.position.set(0,11,-4.6);g.add(this.tower);for(let i=0;i<6;i++){const gear=kit.gear({radius:1.1+i*.24,teeth:16+i*2,color:i%2?'#c4964c':'#8a6329'});gear.position.y=i*1.5;this.tower.add(gear);}const towerLight=new THREE.PointLight('#ffd47b',1,16,2);towerLight.position.set(0,4,0);this.tower.add(towerLight);
  this.apprentice=new ClockmakerApprentice(kit);this.apprentice.group.position.set(-6,0,2.5);this.apprentice.group.rotation.y=Math.PI/2;g.add(this.apprentice.group);
  this.routeFold=experience.effects.blueprintFold({width:6,height:3.2});this.routeFold.position.set(0,2.5,-2.1);g.add(this.routeFold);this.routeMaskPlane=new THREE.Mesh(new THREE.PlaneGeometry(5.85,3.05),new THREE.MeshBasicMaterial({map:kit.asset('blueprintRoute'),transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}));this.routeMaskPlane.position.set(0,2.5,-2.05);g.add(this.routeMaskPlane);
  this.timeField=experience.effects.timeFractureField({radius:1.25});this.timeField.position.set(-2.4,1.35,.95);g.add(this.timeField);
  this.thread=experience.effects.redThreadGlow([new THREE.Vector3(-6,.45,2.5),new THREE.Vector3(-2.4,1.4,.8),new THREE.Vector3(.9,1.3,.15),new THREE.Vector3(3,4,-1),new THREE.Vector3(0,11,-4.5)]);this.thread.visible=false;g.add(this.thread);
  this.clockDust=[];for(let i=0;i<this.tiered(120,74,38);i++){const mote=new THREE.Mesh(new THREE.PlaneGeometry(.02+(i%4)*.01,.02+(i%3)*.012),new THREE.MeshBasicMaterial({color:i%5?'#d9c9a5':'#ffd47b',transparent:true,opacity:.3,depthWrite:false}));mote.userData={base:new THREE.Vector3(-8+(i*37%16),.25+(i%5)*.65,-6+(i*17%12)),phase:i*.35};mote.position.copy(mote.userData.base);g.add(mote);this.clockDust.push(mote);}
  this.cityLight=new THREE.PointLight('#ffd47b',0,20,2);this.cityLight.position.set(-2.4,1.4,.8);g.add(this.cityLight);this.fog=new THREE.Fog('#1b2840',9,48);
 }
 update(p,time){const repair=win(p,.18,.46),chase=win(p,.43,.76),route=win(p,.72,1);const exp=this.experience;exp.renderer.setClearColor('#1b2840');exp.scene.fog=this.fog;exp.lights.hemi.intensity=.42+route*.16;exp.lights.key.intensity=.5+route*.55;exp.lights.rim.intensity=.42;exp.lights.accent.position.set(-2.4,1.4,.8);exp.lights.accent.intensity=.7+repair*2.8;
  this.apprentice.group.position.set(-6+chase*6.7,0,2.5-chase*2.3);this.apprentice.group.rotation.y=Math.PI/2;this.apprentice.setAction(repair>.02?'wind':chase>.02?'run':'walk',time,chase,.18+chase*.32);
  if(repair>.02){this.streetClock.updateMatrixWorld(true);this.apprentice.group.updateMatrixWorld(true);this.crown.getWorldPosition(this._crown);this.apprentice.keyAnchor.getWorldPosition(this._hand);this._delta.subVectors(this._crown,this._hand);this.apprentice.group.position.add(this._delta);}else if(chase>.02){this.looseHand.updateMatrixWorld(true);this.apprentice.group.updateMatrixWorld(true);this.looseAnchor.getWorldPosition(this._minuteAnchor);this.apprentice.right.anchor.getWorldPosition(this._hand);this._delta.subVectors(this._minuteAnchor,this._hand);this.apprentice.group.position.add(this._delta);}
  this.clocks.forEach(({node,phase,base},i)=>{node.userData.minute.rotation.z=-time*(.4+Math.sin(phase)*.3)-(1-repair)*Math.sin(phase)*2.1;node.position.y=base.y+Math.sin(time*.4+phase)*.08*(1-repair);});this.streetClock.userData.minute.rotation.z=-time*(1-repair*.9);this.looseHand.rotation.z=time*(1.4+chase*2);this.looseHand.position.x=.9+Math.sin(time*1.1)*1.8*(1-route);this.train.position.x=-7.3+repair*4.5;this.bridges.forEach((bridge,i)=>{bridge.position.y=bridge.userData.base.y+Math.sin(time*.8+bridge.userData.phase)*(1-repair)*.36;bridge.rotation.z=Math.sin(time*.7+bridge.userData.phase)*(1-repair)*.18;});this.buildings.forEach(({node,base,phase})=>{node.position.y=base.y+Math.sin(time*.5+phase)*(1-repair)*.1;});this.roads.forEach((node)=>{const offset=Math.sin(time*.55+node.userData.phase)*(1-repair)*.32;node.material.opacity=.22+repair*.62;node.position.copy(node.userData.base);node.position.y+=Math.abs(offset)*.18;node.position[node.userData.axis]+=offset;node.rotation.y=(1-repair)*Math.sin(time*.4+node.userData.phase)*.12;});this.cityLamps.forEach(({node,phase})=>{node.material.opacity=repair*(.35+.35*Math.sin(time*1.5+phase));node.scale.setScalar(.25+repair*.55);});this.paperRoutes.forEach(plan=>{plan.position.y=plan.userData.base.y+Math.sin(time*.42+plan.userData.phase)*.12*(1-repair)+route*.48;plan.rotation.z=Math.sin(time*.6+plan.userData.phase)*.14*(1-repair);plan.material.opacity=.35+route*.55;});this.routeTiles.forEach(tile=>{const fold=clamp((route-tile.userData.phase*.06)*2);tile.position.copy(tile.userData.base);tile.position.y+=fold*(.25+(tile.userData.phase%3)*.1);tile.rotation.z=Math.sin(time*.7+tile.userData.phase)*.15*fold;tile.material.opacity=.2+fold*.72;});this.looseTrail.forEach(mark=>{const tail=clamp((chase-mark.userData.offset)*2.8);mark.position.set(this.looseHand.position.x-Math.cos(time*1.4+mark.userData.phase)*tail*(.3+mark.userData.offset),this.looseHand.position.y-Math.sin(time*1.3+mark.userData.phase)*tail*.35,this.looseHand.position.z);mark.rotation.z=time*1.4+mark.userData.phase;mark.material.opacity=tail*.75;});
  this.routeFold.userData.setFold(route,time);this.routeMaskPlane.material.opacity=route*.5;this.timeField.userData.setTimeFracture(1-repair,time);this.thread.visible=route>.03;this.thread.userData.setThread(route);this.clockDust.forEach(mote=>{mote.position.set(mote.userData.base.x+Math.sin(time*.35+mote.userData.phase)*.28,mote.userData.base.y+Math.sin(time*.28+mote.userData.phase)*.18,mote.userData.base.z);mote.material.opacity=.12+route*.42;});this.cityLight.intensity=repair*2.5+route*1.5;this.unspentHour.setMood('discordant');this.unspentHour.setProgress(1-repair);this.unspentHour.update(time,0,1);
  const fov=shot(p,this.experience._pos,this.experience._look);this.experience.camera.set(this.experience._pos,this.experience._look,fov);this.debugState={contacts:this.apprentice.captureContacts(),progress:p,threadVisible:this.thread.visible,repair,chase,route,finite:Number.isFinite(this.apprentice.group.position.x)};
 }
}
