import * as THREE from 'three';
import { ProductionBaseScene } from './ProductionBaseScene.js';
import { ClockmakerApprentice } from './ClockmakerApprentice.js';
import { PocketWatch } from '../PocketWatch.js';
import { MasterClock } from '../MasterClock.js';
import { UnspentHour } from './UnspentHour.js';

const clamp=v=>Math.max(0,Math.min(1,v));const ease=v=>{v=clamp(v);return v*v*(3-2*v)};const win=(p,a,b)=>ease((p-a)/(b-a));
const SHOTS=[
 {at:0,pos:[1,2.2,5],look:[0,3,.1],fov:33},
 {at:.16,pos:[0,4.8,9],look:[0,0,-6],fov:42},
 {at:.36,pos:[-3.6,3.1,7],look:[-.2,1,.1],fov:38},
 {at:.56,pos:[-5.8,5.5,11],look:[0,1,-5],fov:44},
 {at:.78,pos:[-9,8.7,16],look:[0,0,-8],fov:47},
 {at:1,pos:[-14,12,23],look:[0,0,-10],fov:52}
];
function shot(p,pos,look){let i=0;while(i<SHOTS.length-2&&p>=SHOTS[i+1].at)i++;const a=SHOTS[i],b=SHOTS[i+1],t=ease((p-a.at)/(b.at-a.at));pos.set(...a.pos).lerp(new THREE.Vector3(...b.pos),t);look.set(...a.look).lerp(new THREE.Vector3(...b.look),t);return a.fov+(b.fov-a.fov)*t;}

// Production finale: the city must visibly inherit time from the master
// clock. The apprentice's final action is deliberately small—setting the
// mentor's watch down—while the consequence propagates outward.
export class ProductionNewClockTicksScene extends ProductionBaseScene {
 build(){const {group:g,kit}=this;this._hand=new THREE.Vector3();this._watch=new THREE.Vector3();this._delta=new THREE.Vector3();
  /* ---------------- workshop foreground ---------------- */
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(18,13),kit.material('wood','#553c2e'));floor.rotation.x=-Math.PI/2;g.add(floor);this.bench=kit.workbench();this.bench.position.set(-.3,0,.25);g.add(this.bench);
  /* ---------------- the workshop carries its history into dawn ---------------- */
  this.shelves=[];for(const sx of[-5.9,5.9]){const shelf=new THREE.Group();shelf.position.set(sx,2.65,-3.65);g.add(shelf);for(let level=0;level<3;level++){const plank=new THREE.Mesh(new THREE.BoxGeometry(2.25,.12,.46),kit.material('wood','#5b4031'));plank.position.set(0,level*1.05,0);shelf.add(plank);for(let slot=0;slot<3;slot++){const jar=new THREE.Mesh(new THREE.CylinderGeometry(.14,.17,.34,8),kit.material('enamel',slot%2?'#d8c9aa':'#8da5ae',{opacity:.8}));jar.position.set(-.7+slot*.7,level*1.05+.25,.1);shelf.add(jar);}}this.shelves.push(shelf);}
  this.blueprint=kit.blueprint({width:3.5,height:2.4});this.blueprint.rotation.x=-Math.PI/2;this.blueprint.position.set(-.3,1.22,.38);g.add(this.blueprint);
  this.watch=new PocketWatch(kit);this.watch.root.position.set(-.3,1.28,.4);g.add(this.watch.root);this.unspentHour=new UnspentHour(kit,{particleCount:this.tiered(32,20,10),scale:.35}).attachTo(this.watch.root,new THREE.Vector3(0,0,.15));this.watchAnchor=new THREE.Object3D();this.watchAnchor.position.set(0,0,.1);this.watch.root.add(this.watchAnchor);
  this.apprentice=new ClockmakerApprentice(kit);this.apprentice.group.position.set(.2,0,2.05);this.apprentice.group.rotation.y=Math.PI;g.add(this.apprentice.group);
  const windowFrame=new THREE.Mesh(new THREE.BoxGeometry(8.2,5.8,.14),kit.material('wood','#3d2a22'));windowFrame.position.set(0,3.5,-4.05);g.add(windowFrame);const dawn=new THREE.Mesh(new THREE.PlaneGeometry(7.85,5.45),new THREE.MeshBasicMaterial({color:'#e8ac74',transparent:true,opacity:.72,side:THREE.DoubleSide,depthWrite:false}));dawn.position.set(0,3.5,-3.95);g.add(dawn);
  this.mentorReflection=new THREE.Group();this.mentorReflection.position.set(2.7,3.35,-3.86);g.add(this.mentorReflection);const reflectionBody=new THREE.Mesh(new THREE.PlaneGeometry(.75,1.65),new THREE.MeshBasicMaterial({color:'#ffe6ae',transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));this.mentorReflection.add(reflectionBody);const reflectionHead=new THREE.Mesh(new THREE.CircleGeometry(.22,12),new THREE.MeshBasicMaterial({color:'#fff1c7',transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));reflectionHead.position.y=.95;this.mentorReflection.add(reflectionHead);this.mentorReflection.userData={body:reflectionBody,head:reflectionHead};
  /* ---------------- master clock and city consequence ---------------- */
  this.master=new MasterClock(kit);this.master.root.scale.setScalar(.58);this.master.root.position.set(0,2.3,-7.8);g.add(this.master.root);this.master.setFinalHour(1);this.continuityThread=experience.effects.redThreadGlow([new THREE.Vector3(-.3,1.28,.4),new THREE.Vector3(-.6,1.8,-2.5),new THREE.Vector3(0,2.3,-7.5)]);this.continuityThread.visible=false;g.add(this.continuityThread);
  this.city=new THREE.Group();this.city.position.set(0,-5.6,-10);this.city.scale.setScalar(.64);g.add(this.city);this.clocks=[];this.lamps=[];this.smoke=[];this.cityGearTowers=[];for(let i=0;i<60;i++){const building=kit.miniatureBuilding({w:.62+(i%4)*.16,h:.75+(i%5)*.25,d:.7+(i%3)*.14});const x=-5+(i%10)*1.42,z=-4+Math.floor(i/10)*1.35;building.position.set(x,0,z);g.add(building);this.city.add(building);if(i%3===0){const face=kit.clockFace({radius:.18});face.position.set(x,building.position.y+.8,z+.43);this.city.add(face);this.clocks.push({node:face,phase:i*.49});}if(i%4===0){const lamp=new THREE.Sprite(new THREE.SpriteMaterial({color:'#ffd47b',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));lamp.position.set(x+.35,.78,z+.35);lamp.scale.setScalar(.55);this.city.add(lamp);this.lamps.push({node:lamp,phase:i*.33});}if(i%7===0){const gear=kit.gear({radius:.25+(i%3)*.07,teeth:10+(i%4)*2,color:'#b98942'});gear.position.set(x,building.position.y+.45,z-.5);gear.scale.setScalar(.7);this.city.add(gear);this.cityGearTowers.push({node:gear,phase:i*.42});}}
  this.cityRoads=[];for(let i=0;i<8;i++){const road=new THREE.Mesh(new THREE.BoxGeometry(14,.035,.14),kit.material('brass','#3a6079'));road.position.set(0,.12,-4+i*1.35);this.city.add(road);this.cityRoads.push({node:road,phase:i*.39});}
  this.train=kit.train();this.train.position.set(-6,.2,3.1);this.city.add(this.train);const track=new THREE.Mesh(new THREE.BoxGeometry(14,.04,.18),kit.material('brass','#79552f'));track.position.set(0,.12,3.1);this.city.add(track);
  for(let i=0;i<12;i++){const puff=new THREE.Sprite(new THREE.SpriteMaterial({color:'#f6e8cf',transparent:true,opacity:0,depthWrite:false}));puff.position.set(-5+(i%8)*1.42,1.1+Math.floor(i/8)*.6,-4+Math.floor(i/8)*1.35);puff.scale.setScalar(.45);this.city.add(puff);this.smoke.push({node:puff,base:puff.position.clone(),phase:i*.63});}
  this.cityLight=new THREE.PointLight('#ffd47b',0,18,2);this.cityLight.position.set(0,3,0);this.city.add(this.cityLight);
  /* ---------------- tick rings, feather-like time motes ---------------- */
  this.tickRings=[];for(let i=0;i<5;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.3+i*.13,.022,6,32),new THREE.MeshBasicMaterial({color:'#ffe4a3',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));ring.rotation.x=-Math.PI/2;ring.position.set(0,.1,-7.5);g.add(ring);this.tickRings.push(ring);}this.tickWave=experience.effects.tickWave({rings:5});this.tickWave.position.set(0,.1,-7.5);g.add(this.tickWave);
  this.motes=[];for(let i=0;i<this.tiered(160,96,46);i++){const mote=new THREE.Mesh(new THREE.PlaneGeometry(.02+(i%4)*.012,.05+(i%3)*.02),new THREE.MeshBasicMaterial({color:i%5?'#ffd47b':'#f7e2bd',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));mote.userData={base:new THREE.Vector3(-8+(i*29%16),.3+(i*17%7),-6+(i%8)*.4),phase:i*.27};mote.position.copy(mote.userData.base);g.add(mote);this.motes.push(mote);}this.fog=new THREE.Fog('#e4ad79',12,80);
 }
 update(p,time){const tick=win(p,.02,.28),sync=win(p,.18,.62),place=win(p,.54,.82),retreat=win(p,.78,1);const exp=this.experience;exp.renderer.setClearColor('#e4ad79');exp.scene.fog=this.fog;exp.lights.hemi.intensity=.95;exp.lights.key.intensity=.95+tick*.55;exp.lights.rim.intensity=.18;exp.lights.accent.position.set(0,2.3,-7.7);exp.lights.accent.intensity=1+tick*4;
  this.apprentice.group.position.set(.2,0,2.05-place*.62);this.apprentice.group.rotation.y=Math.PI;this.apprentice.setAction(place>.02?'place':'watch',time,place,.06);
  if(place>.02){this.watchAnchor.updateMatrixWorld(true);this.apprentice.group.updateMatrixWorld(true);this.watchAnchor.getWorldPosition(this._watch);this.apprentice.left.anchor.getWorldPosition(this._hand);this._delta.subVectors(this._watch,this._hand);this.apprentice.group.position.add(this._delta);}this.watch.root.position.set(-.3,1.28-place*.06,.4);this.watch.setTime(1,.4+tick*.6);this.continuityThread.visible=place>.05;this.continuityThread.userData.setThread(place*(1-retreat*.25));
  this.master.setFinalHour(1);this.unspentHour.setMood('resolved');this.unspentHour.setProgress(retreat);this.unspentHour.update(time,0,1);this.master.dial.userData.minute.rotation.z=-tick*Math.PI*2;this.clocks.forEach(({node,phase})=>{const wave=clamp((sync-(phase%1)*.42)*2.2);node.userData.minute.rotation.z=-time*(.25+wave*.85);node.userData.hour.rotation.z=-time*.08;});this.train.position.x=-6+sync*12;this.lamps.forEach(({node,phase})=>{const wave=clamp((sync-(phase%1)*.48)*2.2);node.material.opacity=wave*(.35+.3*Math.sin(time*1.5+phase));node.scale.setScalar(.35+wave*.7);});this.smoke.forEach(({node,base,phase})=>{const wave=clamp((sync-(phase%1)*.5)*2.2);node.position.set(base.x+Math.sin(time*.25+phase)*.25,base.y+wave*(.7+Math.sin(time*.4+phase)*.22),base.z);node.material.opacity=wave*.32;});this.cityGearTowers.forEach(({node,phase},i)=>{const wave=clamp((sync-(phase%1)*.45)*2.2);node.rotation.z=time*(.35+wave*.75)+phase;});this.cityRoads.forEach(({node,phase})=>{const wave=clamp((sync-(phase%1)*.4)*2.2);node.material.opacity=.3+wave*.55;node.position.y=.12+Math.sin(time*.3+phase)*.02*(1-wave);});this.cityLight.intensity=sync*3.6;this.shelves.forEach((shelf,i)=>shelf.rotation.z=Math.sin(time*.25+i)*.01*(1-place));this.mentorReflection.userData.body.material.opacity=place*(1-retreat)*.2;this.mentorReflection.userData.head.material.opacity=place*(1-retreat)*.24;this.mentorReflection.position.y=3.35+Math.sin(time*.5)*.025*(1-retreat);
  this.tickRings.forEach((ring,i)=>{const burst=clamp((tick-i*.1)*2.4);ring.scale.setScalar(.6+burst*(6+i*1.3));ring.material.opacity=burst*(1-burst)*.75;});this.tickWave.userData.setTick(tick);this.city.children.forEach(node=>experience.effects.dawnWash(node,sync));this.motes.forEach(mote=>{mote.position.set(mote.userData.base.x+Math.sin(time*.38+mote.userData.phase)*.3,mote.userData.base.y+Math.sin(time*.25+mote.userData.phase)*.2+tick*.6,mote.userData.base.z);mote.material.opacity=.08+tick*.52;});
  const fov=shot(p,this.experience._pos,this.experience._look);this.experience.camera.set(this.experience._pos,this.experience._look,fov);this.debugState={contacts:this.apprentice.captureContacts(),progress:p,tick,sync,place,retreat,finite:Number.isFinite(this.watch.root.position.y)};
 }
}
