import * as THREE from 'three';
import { ProductionBaseScene } from './ProductionBaseScene.js';
import { ClockmakerApprentice } from './ClockmakerApprentice.js';
import { MasterClock } from '../MasterClock.js';
import { UnspentHour } from './UnspentHour.js';
import { PocketWatch } from '../PocketWatch.js';

const clamp=v=>Math.max(0,Math.min(1,v));const ease=v=>{v=clamp(v);return v*v*(3-2*v)};const win=(p,a,b)=>ease((p-a)/(b-a));
const SHOTS=[
 {at:0,pos:[-7,3.8,13],look:[0,4,.1],fov:44},
 {at:.18,pos:[-3.8,2.8,8],look:[0,4,.1],fov:39},
 {at:.36,pos:[2.6,3.25,5.7],look:[0,4.4,.2],fov:33},
 {at:.54,pos:[1.4,4.15,4.2],look:[0,4.7,.25],fov:29},
 {at:.73,pos:[-1.5,5.2,6.8],look:[0,4.3,-.5],fov:38},
 {at:.88,pos:[-5.6,7.6,12],look:[0,2,-6],fov:45},
 {at:1,pos:[-11,10,20],look:[0,0,-9],fov:50}
];
function shot(p,pos,look){let i=0;while(i<SHOTS.length-2&&p>=SHOTS[i+1].at)i++;const a=SHOTS[i],b=SHOTS[i+1],t=ease((p-a.at)/(b.at-a.at));pos.set(...a.pos).lerp(new THREE.Vector3(...b.pos),t);look.set(...a.look).lerp(new THREE.Vector3(...b.look),t);return a.fov+(b.fov-a.fov)*t;}

// Production Final Hour: quiet is a material choice. The space is dense with
// mechanisms but the action is only release, thread, strike, continuation.
export class ProductionFinalHourScene extends ProductionBaseScene {
 build(){const {group:g,kit}=this;this._hand=new THREE.Vector3();this._handLeft=new THREE.Vector3();this._target=new THREE.Vector3();this._targetLeft=new THREE.Vector3();this._delta=new THREE.Vector3();
  /* ---------------- dial chamber / clock architecture ---------------- */
  const floor=new THREE.Mesh(new THREE.CylinderGeometry(10,10,.3,48),kit.material('wood','#4b332a'));floor.position.y=-.15;g.add(floor);
  const inner=new THREE.Mesh(new THREE.CylinderGeometry(8.8,8.8,.04,48),kit.material('paper','#ddd0b0'));inner.position.y=.02;g.add(inner);
  for(let i=0;i<28;i++){const board=new THREE.Mesh(new THREE.BoxGeometry(.38,.025,15.6),kit.material('wood',i%2?'#694a38':'#5a3e31'));board.position.set((i-13.5)*.48,.06,0);g.add(board);}
  this.arches=[];for(let i=0;i<8;i++){const a=i/8*Math.PI*2;const arch=new THREE.Mesh(new THREE.TorusGeometry(8.2,.12,8,32,Math.PI*.82),kit.material('brass',i%2?'#9a7135':'#6e502c'));arch.position.set(Math.cos(a)*1.2,4,Math.sin(a)*1.2-1);arch.rotation.set(0,0,a-Math.PI/2);g.add(arch);this.arches.push({node:arch,phase:i*.7});}
  /* ---------------- master clock / mechanical housing ---------------- */
  this.master=new MasterClock(kit);this.master.root.position.set(0,4,-.45);g.add(this.master.root);this.unspentHour=new UnspentHour(kit,{particleCount:this.tiered(64,40,20),scale:.82}).attachTo(this.master.root,new THREE.Vector3(0,0,.42));this.enamelField=experience.effects.enamelFace({radius:4.05});this.enamelField.position.set(0,4,-.12);g.add(this.enamelField);this.healMask=new THREE.Mesh(new THREE.CircleGeometry(4.02,48),new THREE.MeshBasicMaterial({map:kit.asset('enamelHeal'),transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));this.healMask.position.set(0,4,-.08);g.add(this.healMask);
  this.housing=new THREE.Group();g.add(this.housing);for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const strut=new THREE.Mesh(new THREE.BoxGeometry(.16,3.2,.16),kit.material('brass',i%2?'#b98942':'#805a2b'));strut.position.set(Math.cos(a)*4.9,4+Math.sin(a)*.35,-.7);strut.rotation.z=Math.cos(a)*.08;this.housing.add(strut);}
  this.gearTrain=[];for(let i=0;i<10;i++){const gear=kit.gear({radius:.42+(i%4)*.16,teeth:12+(i%5)*2,color:i%2?'#c4964c':'#8c632c'});const a=i/10*Math.PI*2;gear.position.set(Math.cos(a)*5.6,1.2+(i%3)*1.5,Math.sin(a)*1.2-1);g.add(gear);this.gearTrain.push({node:gear,dir:i%2?1:-1,phase:i*.5});}
  /* ---------------- apprentice, watch and red thread ---------------- */
  this.apprentice=new ClockmakerApprentice(kit);this.apprentice.group.position.set(1.9,0,1.25);this.apprentice.group.rotation.y=-2.2;g.add(this.apprentice.group);
  this.watch=new PocketWatch(kit);this.watch.root.position.set(1.15,1.15,1.45);g.add(this.watch.root);
  this.thread=experience.effects.redThreadGlow([new THREE.Vector3(1.9,1.5,1.1),new THREE.Vector3(.75,3.6,.55),new THREE.Vector3(0,7.55,-.12)]);this.thread.visible=false;g.add(this.thread);this.tickWave=experience.effects.tickWave({rings:5});this.tickWave.position.set(0,.12,-.5);g.add(this.tickWave);
  this.threadMotes=[];for(let i=0;i<this.tiered(72,44,22);i++){const mote=new THREE.Mesh(new THREE.PlaneGeometry(.03+(i%3)*.014,.11+(i%4)*.035),new THREE.MeshBasicMaterial({color:'#c53a35',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));mote.userData={phase:i*.37,offset:(i%11)*.08};g.add(mote);this.threadMotes.push(mote);}
  /* ---------------- city below / receiving time ---------------- */
  this.city=new THREE.Group();this.city.position.set(0,-6.2,-10);this.city.scale.setScalar(.55);g.add(this.city);this.cityClocks=[];this.cityBuildings=[];this.cityLamps=[];for(let i=0;i<48;i++){const building=kit.miniatureBuilding({w:.65+(i%4)*.16,h:.75+(i%5)*.25,d:.72+(i%3)*.14});building.position.set(-5+(i%8)*1.42,0,-3+Math.floor(i/8)*1.36);this.city.add(building);this.cityBuildings.push({node:building,phase:i*.27});if(i%3===0){const face=kit.clockFace({radius:.18});face.position.set(building.position.x,building.position.y+.82,building.position.z+.44);this.city.add(face);this.cityClocks.push({node:face,phase:i*.49});}if(i%4===0){const lamp=new THREE.Sprite(new THREE.SpriteMaterial({color:'#ffd47b',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));lamp.position.set(building.position.x+.32,.72,building.position.z+.3);lamp.scale.setScalar(.5);this.city.add(lamp);this.cityLamps.push({node:lamp,phase:i*.31});}}
  this.train=kit.train();this.train.position.set(-5,.2,3);this.city.add(this.train);this.cityLight=new THREE.PointLight('#ffd47b',0,15,2);this.cityLight.position.set(0,3,0);this.city.add(this.cityLight);
  /* ---------------- strike / beam / atmosphere ---------------- */
  // Enamel chips carry the history of the sealed hour. They close visually
  // as the red hand takes over, rather than leaving a pristine generic dial.
  this.enamelChips=[];for(let i=0;i<32;i++){const chip=new THREE.Mesh(new THREE.PlaneGeometry(.05+(i%4)*.025,.08+(i%5)*.028),kit.material('enamel',i%3?'#d6c29d':'#9a765c'));const a=i/32*Math.PI*2;chip.userData={a,r:3.55+(i%5)*.12,base:new THREE.Vector3(Math.cos(a)*(3.55+(i%5)*.12),4+Math.sin(a)*(3.55+(i%5)*.12),.18)};chip.position.copy(chip.userData.base);chip.rotation.z=a;g.add(chip);this.enamelChips.push(chip);}
  this.blueprints=[];for(let i=0;i<11;i++){const sheet=kit.blueprint({width:1.4+(i%3)*.25,height:.95});sheet.userData={base:new THREE.Vector3(-6+(i%5)*3,2.2+Math.floor(i/5)*1.5,-1.65),phase:i*.61};sheet.position.copy(sheet.userData.base);sheet.rotation.z=(i%4-.5)*.18;g.add(sheet);this.blueprints.push(sheet);}
  this.chains=[];for(const x of[-6.6,-5.8,5.8,6.6]){const chain=new THREE.Group();for(let y=0;y<9;y++){const link=new THREE.Mesh(new THREE.TorusGeometry(.08,.018,5,8),kit.material('brass','#77552c'));link.position.y=y*.86;link.rotation.x=y%2?Math.PI/2:0;chain.add(link);}chain.position.set(x,1.2,-1.1);g.add(chain);this.chains.push(chain);}
  this.strikeRings=[];for(let i=0;i<4;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.4+i*.12,.025,6,32),new THREE.MeshBasicMaterial({color:'#ffe4a3',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));ring.rotation.x=-Math.PI/2;ring.position.set(0,.12,-.5);g.add(ring);this.strikeRings.push(ring);}
  this.cityGlow=[];this.city.children.forEach((node,i)=>{if(i%5===0){const glow=new THREE.Sprite(new THREE.SpriteMaterial({color:'#ffd47b',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));glow.position.copy(node.position).add(new THREE.Vector3(0,.85,.1));glow.scale.setScalar(.7);this.city.add(glow);this.cityGlow.push({node:glow,phase:i*.33});}});
  this.strikeLight=new THREE.PointLight('#ffd47b',0,30,2);this.strikeLight.position.set(0,4,.2);g.add(this.strikeLight);this.dust=[];for(let i=0;i<this.tiered(140,86,42);i++){const mote=new THREE.Mesh(new THREE.PlaneGeometry(.02+(i%4)*.011,.02+(i%3)*.01),new THREE.MeshBasicMaterial({color:'#e8d4ae',transparent:true,opacity:.3,depthWrite:false}));mote.userData={base:new THREE.Vector3(-8+(i*29%16),.4+(i*17%8),-1.5+(i%7)*.3),phase:i*.31};mote.position.copy(mote.userData.base);g.add(mote);this.dust.push(mote);}this.fog=new THREE.Fog('#1b2840',9,58);
 }
 update(p,time){const approach=win(p,.02,.3),release=win(p,.28,.55),thread=win(p,.48,.78),strike=win(p,.72,1);const exp=this.experience;exp.renderer.setClearColor('#1b2840');exp.scene.fog=this.fog;exp.lights.hemi.intensity=.4+strike*.45;exp.lights.key.intensity=.5+strike*1.2;exp.lights.rim.intensity=.42;exp.lights.accent.position.set(0,4,.2);exp.lights.accent.intensity=.8+strike*5;
  this.apprentice.group.position.set(1.9-approach*.75,0,1.25-approach*.5);this.apprentice.group.rotation.y=-2.2+approach*.14;this.apprentice.setAction(thread>.02?'thread':release>.02?'place':'watch',time,thread,.15+thread*.5);
  const rightTarget=thread>.02?this.master.threadAnchorRight:this.master.releaseAnchorRight;const leftTarget=thread>.02?this.master.threadAnchorLeft:this.master.releaseAnchorLeft;this.master.root.updateMatrixWorld(true);this.apprentice.group.updateMatrixWorld(true);rightTarget.getWorldPosition(this._target);leftTarget.getWorldPosition(this._targetLeft);this.apprentice.right.anchor.getWorldPosition(this._hand);this.apprentice.left.anchor.getWorldPosition(this._handLeft);this._target.add(this._targetLeft).multiplyScalar(.5);this._hand.add(this._handLeft).multiplyScalar(.5);this._delta.subVectors(this._target,this._hand);this.apprentice.group.position.add(this._delta);
  this.master.setFinalHour(Math.max(release,thread));this.unspentHour.setMood('releasing');this.unspentHour.setProgress(Math.max(release,thread));this.unspentHour.update(time,0,1);this.enamelField.userData.setEnamel(.9,thread);this.healMask.material.opacity=thread*.52;this.thread.visible=thread>.02;this.thread.userData.setThread(thread);this.tickWave.userData.setTick(strike);this.watch.setTime(.72+strike*.28,.45+strike*.55);this.watch.root.position.set(1.15,1.15-thread*.7,1.45+thread*.28);
  this.gearTrain.forEach(({node,dir,phase})=>node.rotation.z=dir*(time*.45+strike*(1+phase*.16)));this.arches.forEach(({node,phase})=>node.rotation.z=Math.sin(time*.2+phase)*.018*(1-strike));this.cityClocks.forEach(({node,phase})=>{node.userData.minute.rotation.z=-time*(.3+strike*.8)-Math.sin(phase)*(1-strike)*1.6;node.userData.hour.rotation.z=-time*.08;});this.train.position.x=-5+strike*10;this.cityLight.intensity=strike*3.2;this.cityLamps.forEach(({node,phase})=>{node.material.opacity=strike*(.25+.35*Math.sin(time*2+phase));node.scale.setScalar(.4+strike*.8);});this.cityBuildings.forEach(({node,phase})=>{node.position.y=Math.sin(time*.4+phase)*(1-strike)*.05;});
  this.enamelChips.forEach((chip,i)=>{const heal=ease(clamp((thread-i*.018)*2.4));chip.position.copy(chip.userData.base).multiplyScalar(1-heal*.13);chip.material.opacity=1-heal*.88;});this.blueprints.forEach(sheet=>{sheet.position.y=sheet.userData.base.y+Math.sin(time*.48+sheet.userData.phase)*.16*(1-strike);sheet.rotation.z=Math.sin(time*.6+sheet.userData.phase)*.13*(1-strike);sheet.material.opacity=.65+strike*.28;});this.chains.forEach((chain,i)=>chain.rotation.z=Math.sin(time*.45+i)*.025*(1-strike));
  this.strikeRings.forEach((ring,i)=>{const burst=clamp((strike-i*.12)*2.2);ring.scale.setScalar(.5+burst*(5+i*1.5));ring.material.opacity=burst*(1-burst)*.72;});this.cityGlow.forEach(({node,phase})=>{node.material.opacity=strike*(.35+.25*Math.sin(time*2+phase));node.scale.setScalar(.55+strike*.9);});
  this.threadMotes.forEach((mote,i)=>{const launch=clamp((thread-mote.userData.offset)*2.8);const a=time*1.2+mote.userData.phase;mote.position.set(.2+Math.cos(a)*launch*(1.2+(i%4)*.2),4.2+launch*(2.8+(i%5)*.22),-.1+Math.sin(a)*launch*1.2);mote.material.opacity=launch*.82;});this.dust.forEach(mote=>{mote.position.set(mote.userData.base.x+Math.sin(time*.35+mote.userData.phase)*.3,mote.userData.base.y+Math.sin(time*.2+mote.userData.phase)*.24,mote.userData.base.z);mote.material.opacity=.12+strike*.35;});this.strikeLight.intensity=.8+strike*5;
  const fov=shot(p,this.experience._pos,this.experience._look);this.experience.camera.set(this.experience._pos,this.experience._look,fov);this.debugState={contacts:this.apprentice.captureContacts(),progress:p,redHand:this.master.redHand.visible,threadVisible:this.thread.visible,finite:Number.isFinite(this.apprentice.group.position.x),citySync:strike};
 }
}
